# Jekyll Settings

title: The life of a Tinkerer
description: Personal Webpage of Cameron Buss
email: camrbuss@vt.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://camrbuss.github.io/camsite/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  camrbuss

sass:
  sass_dir: _sass
  style: compressed

# Build settings
